CREATE TABLE `calendar_attendance_sync_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(30) NOT NULL DEFAULT 'running',
  `active_key` VARCHAR(30) NULL,
  `window_start` DATETIME(3) NOT NULL,
  `window_end` DATETIME(3) NOT NULL,
  `calendars_total` INT NOT NULL DEFAULT 0,
  `calendars_processed` INT NOT NULL DEFAULT 0,
  `students_updated` INT NOT NULL DEFAULT 0,
  `hocmai_updated` INT NOT NULL DEFAULT 0,
  `calendars_failed` INT NOT NULL DEFAULT 0,
  `errors_json` LONGTEXT NULL,
  `heartbeat_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `finished_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_calendar_attendance_sync_active_key` (`active_key`),
  KEY `idx_calendar_attendance_sync_started_at` (`started_at`),
  KEY `idx_calendar_attendance_sync_window_start` (`window_start`)
);
