-- Audit lịch sử phân lớp được hoãn. Logic phân lớp hiện chỉ cập nhật
-- users.room_id và users.class_id, nên không cần tạo bảng ở giai đoạn này.
-- Khi cần audit, thêm một migration mới để tạo classroom_assignment_history.
